// next imports
import type { Metadata } from 'next'
// styles
import '@/styles/globals.css'
// components
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'


export const metadata: Metadata = {
  title: 'kid esports',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
