

// next imports
import type { Metadata } from 'next'
// react imports 
// styles
import '@/styles/globals.css'
// components
import Footer from '@/components/Footer/Footer'
import Navbar from '@/components/Navbar/Navbar'
// toast imports
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
// firebase imports
import { AuthContextProvider } from '@/contexts/useAuthContext'

export const metadata: Metadata = {
  title: 'kid esports',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <AuthContextProvider>
      <html lang="en">
        <body>
          <Navbar />
          <main className='max-w-screen min-h-screen flex-center'>
            {children}
          </main>
          <Footer />
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
        </body>
      </html>
    </AuthContextProvider>
  )
}
