// next imports
import type { Metadata } from 'next'
// styles
import '@/styles/globals.css'
// components
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
// toast imports
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";


export const metadata: Metadata = {
  title: 'kid esports',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
        {/* <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        /> */}
      </body>
    </html>
  )
}
